import test from 'node:test';
import assert from 'node:assert/strict';
import {Flight,STEP,WATER} from '../src/flight.js';
function empty(){const m=new Flight(123);m.sparks=[];m.balloons=[];m.bubbles=[];return m;}
test('horizontal input accelerates, opposite input brakes before reversing',()=>{const m=empty();m.player.vx=130;m.step(STEP,-1);assert.ok(m.player.vx>0&&m.player.vx<130);for(let i=0;i<80;i++){m.player.y=300;m.player.vy=0;m.step(STEP,-1);}assert.ok(m.player.vx<0);});
test('releasing movement retains drift rather than stopping',()=>{const m=empty();m.player.vx=100;const x=m.player.x;m.step(STEP,0);assert.ok(m.player.vx>99);assert.ok(m.player.x>x);});
test('flap adds lift to existing momentum; gravity eventually reverses ascent',()=>{const m=empty();m.player.vy=40;m.flap();assert.equal(m.player.vy,-30);for(let i=0;i<40;i++)m.step(STEP);assert.ok(m.player.vy>0);});
test('held lift repeats at a bounded cadence, never escapes through the ceiling',()=>{const m=empty();for(let i=0;i<120*10;i++)m.step(STEP,0,true);assert.ok(m.alive);assert.ok(m.player.y>=76);assert.ok(m.player.vy>=-172);});
test('water contact ends play and dead simulation cannot accrue rewards',()=>{const m=empty();m.player.y=WATER-12;assert.equal(m.step(STEP)[0].type,'hit');const points=m.score;assert.deepEqual(m.step(1),[]);assert.equal(m.score,points);});
test('either balloon touching a spark ends the run',()=>{const m=empty();const p=m.player;m.sparks=[{baseX:p.x-11,baseY:p.y-34,x:p.x-11,y:p.y-34,r:7,amplitude:0,horizontal:0,rate:1,phase:0}];assert.equal(m.step(STEP)[0].type,'hit');});
test('collectibles award once and a perfect twenty gives a bonus',()=>{const m=empty();for(let i=0;i<20;i++){m.player.y=300;m.player.vy=0;m.balloons=[{x:m.player.x,y:282,taken:false,missed:false}];const es=m.step(STEP);assert.ok(es.some(e=>e.type==='balloon'));if(i===19)assert.equal(es.find(e=>e.type==='balloon').bonus,1000);m.step(STEP);}assert.equal(m.collected,20);assert.ok(m.score>=3000&&m.score<3008);});
test('missing a balloon only resets chain after it leaves the screen',()=>{const m=empty();m.streak=5;m.balloons=[{x:m.width+23,y:300,taken:false,missed:false}];m.step(STEP);assert.equal(m.streak,5);for(let i=0;i<6;i++)m.step(STEP);assert.equal(m.streak,0);});
test('bubble pauses scrolling while steering and gravity remain active',()=>{const m=empty();m.bubbles=[{x:m.player.x,y:m.player.y,taken:false}];assert.ok(m.step(STEP).some(e=>e.type==='bubble'));const d=m.distance;m.player.vx=50;const x=m.player.x;m.step(STEP);assert.equal(m.distance,d);assert.ok(m.player.x>x);assert.ok(m.player.vy>0);});
test('same seed reproduces course and new seeds change it',()=>{assert.deepEqual(new Flight(45).sparks,new Flight(45).sparks);assert.notDeepEqual(new Flight(45).sparks,new Flight(46).sparks);});
test('moving hazards have continuous, bounded motion',()=>{const m=new Flight(4);const moving=m.sparks.find(s=>s.amplitude>0);const original=moving.baseY;for(let i=0;i<120;i++){m.player.y=300;m.player.vy=0;m.player.x=m.width-30;m.step(STEP);}assert.ok(Math.abs(moving.y-original)<=moving.amplitude);assert.notEqual(moving.y,original);});
test('generated safe bands account for spark travel, player balloon height, and change gradually',()=>{for(let seed=0;seed<60;seed++){const m=new Flight(seed);for(let n=0;n<100;n++)m.addColumn(-2000-n*180);for(let i=1;i<m.columns.length;i++)assert.ok(Math.abs(m.columns[i].safeY-m.columns[i-1].safeY)<=75);for(const c of m.columns)for(const s of m.sparks.filter(s=>Math.abs(s.baseX-c.x)<30)){assert.ok(Math.abs(s.baseY-c.safeY)-s.amplitude>60);}}});
test('fish telegraph gives time to escape from the surface',()=>{const m=empty();for(let i=0;i<80;i++){m.player.y=WATER-55;m.player.vy=0;m.step(STEP);}assert.ok(m.fish);assert.ok(m.alive);m.player.y=300;for(let i=0;i<120;i++){m.player.y=300;m.player.vy=0;m.step(STEP);}assert.ok(m.alive);});
